# Default Configuration for tinySA-LO Power Characterization
# Override these values with command-line arguments

# Serial Ports
arduino_port: /dev/cu.usbserial-14110  # Update to match your Arduino port
tinysa_port: auto  # 'auto' for automatic detection, or specify port

# Frequency Sweep Parameters
freq_start: 900.0   # MHz - start frequency
freq_stop: 960.0    # MHz - stop frequency  
freq_step: 0.2      # MHz - step size (301 points total)

# Local Oscillator Settings
lo_power: +5        # dBm - output power setting (+5 or -4 typical)

# Timing Parameters
settling_time: 0.1  # seconds - wait after frequency change for LO to settle
measurement_time: 0.05  # seconds - per tinySA measurement

# tinySA Measurement Settings
span: 1.0           # MHz - measurement span around target frequency
rbw: auto           # Resolution bandwidth ('auto' or value in kHz)
averaging: 4        # Number of averages (1, 4, or 16)
attenuation: auto   # Input attenuation ('auto' or 0-31 dB)

# Output Settings
output_format: csv  # 'csv' or 'fits'
output_dir: results # Directory for output files
timestamp_format: '%Y%m%d_%H%M%S'  # Format for timestamp in filename
